<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminEmailTokenListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'Terminal42\NotificationCenterBundle\EventListener\AdminEmailTokenListener' shared service.
     *
     * @return \Terminal42\NotificationCenterBundle\EventListener\AdminEmailTokenListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/EventListener/AdminEmailTokenListener.php';

        $a = ($container->services['contao.framework'] ?? $container->getContao_FrameworkService());

        if (isset($container->privates['Terminal42\\NotificationCenterBundle\\EventListener\\AdminEmailTokenListener'])) {
            return $container->privates['Terminal42\\NotificationCenterBundle\\EventListener\\AdminEmailTokenListener'];
        }

        return $container->privates['Terminal42\\NotificationCenterBundle\\EventListener\\AdminEmailTokenListener'] = new \Terminal42\NotificationCenterBundle\EventListener\AdminEmailTokenListener(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->privates['Terminal42\\NotificationCenterBundle\\Token\\Definition\\Factory\\ChainTokenDefinitionFactory'] ?? $container->load('getChainTokenDefinitionFactoryService')), $a);
    }
}
