<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAjaxActionsListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Terminal42\DcawizardBundle\EventListener\AjaxActionsListener' shared autowired service.
     *
     * @return \Terminal42\DcawizardBundle\EventListener\AjaxActionsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/dcawizard/src/EventListener/AjaxActionsListener.php';

        return $container->services['Terminal42\\DcawizardBundle\\EventListener\\AjaxActionsListener'] = new \Terminal42\DcawizardBundle\EventListener\AjaxActionsListener(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService()));
    }
}
