<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackendMenuListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'Terminal42\NotificationCenterBundle\EventListener\Backend\BackendMenuListener' shared service.
     *
     * @return \Terminal42\NotificationCenterBundle\EventListener\Backend\BackendMenuListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/EventListener/Backend/BackendMenuListener.php';

        $a = ($container->services['assets.packages'] ?? $container->getAssets_PackagesService());

        if (isset($container->privates['Terminal42\\NotificationCenterBundle\\EventListener\\Backend\\BackendMenuListener'])) {
            return $container->privates['Terminal42\\NotificationCenterBundle\\EventListener\\Backend\\BackendMenuListener'];
        }

        return $container->privates['Terminal42\\NotificationCenterBundle\\EventListener\\Backend\\BackendMenuListener'] = new \Terminal42\NotificationCenterBundle\EventListener\Backend\BackendMenuListener($a);
    }
}
