<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBulkyItemStorageService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'Terminal42\NotificationCenterBundle\BulkyItem\BulkyItemStorage' shared service.
     *
     * @return \Terminal42\NotificationCenterBundle\BulkyItem\BulkyItemStorage
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/BulkyItem/BulkyItemStorage.php';

        $a = ($container->privates['contao.filesystem.virtual.notification_center_bulky_items_storage'] ?? $container->load('getContao_Filesystem_Virtual_NotificationCenterBulkyItemsStorageService'));

        if (isset($container->privates['Terminal42\\NotificationCenterBundle\\BulkyItem\\BulkyItemStorage'])) {
            return $container->privates['Terminal42\\NotificationCenterBundle\\BulkyItem\\BulkyItemStorage'];
        }
        $b = ($container->services['router'] ?? $container->getRouterService());

        if (isset($container->privates['Terminal42\\NotificationCenterBundle\\BulkyItem\\BulkyItemStorage'])) {
            return $container->privates['Terminal42\\NotificationCenterBundle\\BulkyItem\\BulkyItemStorage'];
        }

        return $container->privates['Terminal42\\NotificationCenterBundle\\BulkyItem\\BulkyItemStorage'] = new \Terminal42\NotificationCenterBundle\BulkyItem\BulkyItemStorage($a, $b, ($container->services['uri_signer'] ?? ($container->services['uri_signer'] = new \Symfony\Component\HttpKernel\UriSigner($container->getEnv('APP_SECRET')))), 7);
    }
}
