<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChainTokenDefinitionFactoryService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'Terminal42\NotificationCenterBundle\Token\Definition\Factory\ChainTokenDefinitionFactory' shared service.
     *
     * @return \Terminal42\NotificationCenterBundle\Token\Definition\Factory\ChainTokenDefinitionFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/Token/Definition/Factory/TokenDefinitionFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/Token/Definition/Factory/ChainTokenDefinitionFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/Token/Definition/Factory/CoreTokenDefinitionFactory.php';

        $container->privates['Terminal42\\NotificationCenterBundle\\Token\\Definition\\Factory\\ChainTokenDefinitionFactory'] = $instance = new \Terminal42\NotificationCenterBundle\Token\Definition\Factory\ChainTokenDefinitionFactory();

        $instance->addFactory(new \Terminal42\NotificationCenterBundle\Token\Definition\Factory\CoreTokenDefinitionFactory());

        return $instance;
    }
}
