<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Image_SizesService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'contao.image.sizes' shared service.
     *
     * @return \Contao\CoreBundle\Image\ImageSizes
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Image/ImageSizes.php';

        $container->services['contao.image.sizes'] = $instance = new \Contao\CoreBundle\Image\ImageSizes(($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService()), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->services['contao.framework'] ?? $container->getContao_FrameworkService()), ($container->services['translator'] ?? $container->getTranslatorService()));

        $instance->setPredefinedSizes(['_image_text_full' => ['width' => 1626, 'height' => 1135, 'resizeMode' => 'box', 'formats' => [], 'items' => []], '_image_text' => ['width' => 812, 'height' => 512, 'resizeMode' => 'crop', 'formats' => [], 'items' => []], '_image_slider' => ['width' => 837, 'height' => 623, 'resizeMode' => 'crop', 'formats' => [], 'items' => []], '_icon_boxes_image' => ['width' => 960, 'height' => 476, 'resizeMode' => 'box', 'formats' => [], 'items' => []], '_testimonial_image' => ['width' => 426, 'height' => 602, 'resizeMode' => 'crop', 'formats' => [], 'items' => []], '_icon_with_text' => ['width' => 384, 'height' => 384, 'resizeMode' => 'box', 'items' => [0 => ['media' => '(max-width: 767px)', 'width' => 250, 'height' => 250, 'resizeMode' => 'box']], 'formats' => []], '_testimonial_logo' => ['width' => 105, 'height' => 105, 'resizeMode' => 'box', 'formats' => [], 'items' => []], '_news_list' => ['width' => 742, 'height' => 385, 'resizeMode' => 'crop', 'formats' => [], 'items' => []]]);

        return $instance;
    }
}
