<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateWidgetService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'MenAtWork\MultiColumnWizardBundle\EventListener\Mcw\CreateWidget' shared service.
     *
     * @return \MenAtWork\MultiColumnWizardBundle\EventListener\Mcw\CreateWidget
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/menatwork/contao-multicolumnwizard-bundle/src/EventListener/Mcw/CreateWidget.php';

        return $container->privates['MenAtWork\\MultiColumnWizardBundle\\EventListener\\Mcw\\CreateWidget'] = new \MenAtWork\MultiColumnWizardBundle\EventListener\Mcw\CreateWidget(($container->services['monolog.logger.contao'] ?? $container->load('getMonolog_Logger_ContaoService')));
    }
}
