<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigLoaderService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'Terminal42\NotificationCenterBundle\Config\ConfigLoader' shared service.
     *
     * @return \Terminal42\NotificationCenterBundle\Config\ConfigLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/Config/ConfigLoader.php';

        $a = ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService());

        if (isset($container->privates['Terminal42\\NotificationCenterBundle\\Config\\ConfigLoader'])) {
            return $container->privates['Terminal42\\NotificationCenterBundle\\Config\\ConfigLoader'];
        }

        return $container->privates['Terminal42\\NotificationCenterBundle\\Config\\ConfigLoader'] = new \Terminal42\NotificationCenterBundle\Config\ConfigLoader($a);
    }
}
