<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Image_PictureFactoryService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'contao.image.picture_factory' shared service.
     *
     * @return \Contao\CoreBundle\Image\PictureFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Image/PictureFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Image/PictureFactory.php';

        $a = ($container->services['contao.image.picture_generator'] ?? $container->load('getContao_Image_PictureGeneratorService'));

        if (isset($container->services['contao.image.picture_factory'])) {
            return $container->services['contao.image.picture_factory'];
        }
        $b = ($container->services['contao.image.factory'] ?? $container->load('getContao_Image_FactoryService'));

        if (isset($container->services['contao.image.picture_factory'])) {
            return $container->services['contao.image.picture_factory'];
        }
        $c = ($container->services['contao.framework'] ?? $container->getContao_FrameworkService());

        if (isset($container->services['contao.image.picture_factory'])) {
            return $container->services['contao.image.picture_factory'];
        }

        $container->services['contao.image.picture_factory'] = $instance = new \Contao\CoreBundle\Image\PictureFactory($a, $b, $c, false, $container->parameters['contao.image.imagine_options']);

        $instance->setPredefinedSizes(['_image_text_full' => ['width' => 1626, 'height' => 1135, 'resizeMode' => 'box', 'formats' => [], 'items' => []], '_image_text' => ['width' => 812, 'height' => 512, 'resizeMode' => 'crop', 'formats' => [], 'items' => []], '_image_slider' => ['width' => 837, 'height' => 623, 'resizeMode' => 'crop', 'formats' => [], 'items' => []], '_icon_boxes_image' => ['width' => 960, 'height' => 476, 'resizeMode' => 'box', 'formats' => [], 'items' => []], '_testimonial_image' => ['width' => 426, 'height' => 602, 'resizeMode' => 'crop', 'formats' => [], 'items' => []], '_icon_with_text' => ['width' => 384, 'height' => 384, 'resizeMode' => 'box', 'items' => [0 => ['media' => '(max-width: 767px)', 'width' => 250, 'height' => 250, 'resizeMode' => 'box']], 'formats' => []], '_testimonial_logo' => ['width' => 105, 'height' => 105, 'resizeMode' => 'box', 'formats' => [], 'items' => []], '_news_list' => ['width' => 742, 'height' => 385, 'resizeMode' => 'crop', 'formats' => [], 'items' => []]]);

        return $instance;
    }
}
