<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Image_FactoryService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'contao.image.factory' shared service.
     *
     * @return \Contao\CoreBundle\Image\ImageFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Image/ImageFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Image/ImageFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/imagine/imagine/src/Factory/ClassFactoryAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/imagine/imagine/src/Image/ImagineInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/imagine/imagine/src/Image/AbstractImagine.php';
        include_once \dirname(__DIR__, 4).'/vendor/imagine/imagine/src/Driver/InfoProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/imagine/imagine/src/Gd/Imagine.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/imagine-svg/src/Imagine.php';

        $a = ($container->services['contao.image.legacy_resizer'] ?? $container->load('getContao_Image_LegacyResizerService'));

        if (isset($container->services['contao.image.factory'])) {
            return $container->services['contao.image.factory'];
        }
        $b = ($container->services['contao.framework'] ?? $container->getContao_FrameworkService());

        if (isset($container->services['contao.image.factory'])) {
            return $container->services['contao.image.factory'];
        }

        $container->services['contao.image.factory'] = $instance = new \Contao\CoreBundle\Image\ImageFactory($a, ($container->services['contao.image.imagine'] ?? ($container->services['contao.image.imagine'] = new \Imagine\Gd\Imagine())), ($container->services['contao.image.imagine_svg'] ?? ($container->services['contao.image.imagine_svg'] = new \Contao\ImagineSvg\Imagine())), ($container->services['.container.private.filesystem'] ?? ($container->services['.container.private.filesystem'] = new \Symfony\Component\Filesystem\Filesystem())), $b, false, $container->parameters['contao.image.imagine_options'], $container->parameters['contao.image.valid_extensions'], (\dirname(__DIR__, 4).'/files'), ($container->services['monolog.logger.contao.error'] ?? $container->load('getMonolog_Logger_Contao_ErrorService')));

        $instance->setPredefinedSizes(['_image_text_full' => ['width' => 1626, 'height' => 1135, 'resizeMode' => 'box', 'formats' => [], 'items' => []], '_image_text' => ['width' => 812, 'height' => 512, 'resizeMode' => 'crop', 'formats' => [], 'items' => []], '_image_slider' => ['width' => 837, 'height' => 623, 'resizeMode' => 'crop', 'formats' => [], 'items' => []], '_icon_boxes_image' => ['width' => 960, 'height' => 476, 'resizeMode' => 'box', 'formats' => [], 'items' => []], '_testimonial_image' => ['width' => 426, 'height' => 602, 'resizeMode' => 'crop', 'formats' => [], 'items' => []], '_icon_with_text' => ['width' => 384, 'height' => 384, 'resizeMode' => 'box', 'items' => [0 => ['media' => '(max-width: 767px)', 'width' => 250, 'height' => 250, 'resizeMode' => 'box']], 'formats' => []], '_testimonial_logo' => ['width' => 105, 'height' => 105, 'resizeMode' => 'box', 'formats' => [], 'items' => []], '_news_list' => ['width' => 742, 'height' => 385, 'resizeMode' => 'crop', 'formats' => [], 'items' => []]]);

        return $instance;
    }
}
