<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContaoApiServiceService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'MenAtWork\MultiColumnWizardBundle\Service\ContaoApiService' shared service.
     *
     * @return \MenAtWork\MultiColumnWizardBundle\Service\ContaoApiService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/menatwork/contao-multicolumnwizard-bundle/src/Service/ContaoApiService.php';

        return $container->services['MenAtWork\\MultiColumnWizardBundle\\Service\\ContaoApiService'] = new \MenAtWork\MultiColumnWizardBundle\Service\ContaoApiService(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->services['contao.routing.scope_matcher'] ?? $container->getContao_Routing_ScopeMatcherService()));
    }
}
