<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCloseModalListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Terminal42\DcawizardBundle\EventListener\CloseModalListener' shared autowired service.
     *
     * @return \Terminal42\DcawizardBundle\EventListener\CloseModalListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/dcawizard/src/EventListener/CloseModalListener.php';

        return $container->services['Terminal42\\DcawizardBundle\\EventListener\\CloseModalListener'] = new \Terminal42\DcawizardBundle\EventListener\CloseModalListener(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
