<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDownloadBulkyItemControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Terminal42\NotificationCenterBundle\Controller\DownloadBulkyItemController' shared service.
     *
     * @return \Terminal42\NotificationCenterBundle\Controller\DownloadBulkyItemController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/Controller/DownloadBulkyItemController.php';

        return $container->services['Terminal42\\NotificationCenterBundle\\Controller\\DownloadBulkyItemController'] = new \Terminal42\NotificationCenterBundle\Controller\DownloadBulkyItemController(($container->services['uri_signer'] ?? ($container->services['uri_signer'] = new \Symfony\Component\HttpKernel\UriSigner($container->getEnv('APP_SECRET')))), ($container->privates['Terminal42\\NotificationCenterBundle\\BulkyItem\\BulkyItemStorage'] ?? $container->load('getBulkyItemStorageService')));
    }
}
