<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineOrmHelperService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Codefog\HasteBundle\DoctrineOrmHelper' shared autowired service.
     *
     * @return \Codefog\HasteBundle\DoctrineOrmHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/codefog/contao-haste/src/DoctrineOrmHelper.php';

        $a = ($container->services['contao.framework'] ?? $container->getContao_FrameworkService());

        if (isset($container->services['Codefog\\HasteBundle\\DoctrineOrmHelper'])) {
            return $container->services['Codefog\\HasteBundle\\DoctrineOrmHelper'];
        }
        $b = ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService());

        if (isset($container->services['Codefog\\HasteBundle\\DoctrineOrmHelper'])) {
            return $container->services['Codefog\\HasteBundle\\DoctrineOrmHelper'];
        }
        $c = ($container->services['Codefog\\HasteBundle\\DcaRelationsManager'] ?? $container->load('getDcaRelationsManagerService'));

        if (isset($container->services['Codefog\\HasteBundle\\DoctrineOrmHelper'])) {
            return $container->services['Codefog\\HasteBundle\\DoctrineOrmHelper'];
        }
        $d = ($container->services['router'] ?? $container->getRouterService());

        if (isset($container->services['Codefog\\HasteBundle\\DoctrineOrmHelper'])) {
            return $container->services['Codefog\\HasteBundle\\DoctrineOrmHelper'];
        }

        return $container->services['Codefog\\HasteBundle\\DoctrineOrmHelper'] = new \Codefog\HasteBundle\DoctrineOrmHelper($a, $b, $c, $d, ($container->services['.container.private.security.token_storage'] ?? $container->get_Container_Private_Security_TokenStorageService()));
    }
}
