<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDcaRelationsManagerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Codefog\HasteBundle\DcaRelationsManager' shared autowired service.
     *
     * @return \Codefog\HasteBundle\DcaRelationsManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/codefog/contao-haste/src/DcaRelationsManager.php';

        $a = ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService());

        if (isset($container->services['Codefog\\HasteBundle\\DcaRelationsManager'])) {
            return $container->services['Codefog\\HasteBundle\\DcaRelationsManager'];
        }
        $b = ($container->services['contao.framework'] ?? $container->getContao_FrameworkService());

        if (isset($container->services['Codefog\\HasteBundle\\DcaRelationsManager'])) {
            return $container->services['Codefog\\HasteBundle\\DcaRelationsManager'];
        }
        $c = ($container->services['Codefog\\HasteBundle\\Formatter'] ?? $container->getFormatterService());

        if (isset($container->services['Codefog\\HasteBundle\\DcaRelationsManager'])) {
            return $container->services['Codefog\\HasteBundle\\DcaRelationsManager'];
        }
        $d = ($container->services['Codefog\\HasteBundle\\UndoManager'] ?? $container->load('getUndoManagerService'));

        if (isset($container->services['Codefog\\HasteBundle\\DcaRelationsManager'])) {
            return $container->services['Codefog\\HasteBundle\\DcaRelationsManager'];
        }
        $e = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        if (isset($container->services['Codefog\\HasteBundle\\DcaRelationsManager'])) {
            return $container->services['Codefog\\HasteBundle\\DcaRelationsManager'];
        }

        return $container->services['Codefog\\HasteBundle\\DcaRelationsManager'] = new \Codefog\HasteBundle\DcaRelationsManager($a, $b, $c, ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->services['contao.resource_finder'] ?? $container->getContao_ResourceFinderService()), ($container->services['contao.routing.scope_matcher'] ?? $container->getContao_Routing_ScopeMatcherService()), $d, $e);
    }
}
