<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDcaAjaxOperationsListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Codefog\HasteBundle\EventListener\DcaAjaxOperationsListener' shared autowired service.
     *
     * @return \Codefog\HasteBundle\EventListener\DcaAjaxOperationsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/codefog/contao-haste/src/EventListener/DcaAjaxOperationsListener.php';

        return $container->services['Codefog\\HasteBundle\\EventListener\\DcaAjaxOperationsListener'] = new \Codefog\HasteBundle\EventListener\DcaAjaxOperationsListener(($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService()), ($container->services['assets.packages'] ?? $container->getAssets_PackagesService()), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->services['contao.routing.scope_matcher'] ?? $container->getContao_Routing_ScopeMatcherService()), ($container->services['.container.private.security.authorization_checker'] ?? $container->get_Container_Private_Security_AuthorizationCheckerService()), ($container->services['contao.csrf.token_manager'] ?? $container->getContao_Csrf_TokenManagerService()));
    }
}
