<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDcaDateRangeFilterListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Codefog\HasteBundle\EventListener\DcaDateRangeFilterListener' shared autowired service.
     *
     * @return \Codefog\HasteBundle\EventListener\DcaDateRangeFilterListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/codefog/contao-haste/src/EventListener/DcaDateRangeFilterListener.php';

        return $container->services['Codefog\\HasteBundle\\EventListener\\DcaDateRangeFilterListener'] = new \Codefog\HasteBundle\EventListener\DcaDateRangeFilterListener(($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService()), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->services['contao.routing.scope_matcher'] ?? $container->getContao_Routing_ScopeMatcherService()));
    }
}
