<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExtractorResolverService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'Hofff\Contao\SocialTags\Data\ExtractorResolver' shared service.
     *
     * @return \Hofff\Contao\SocialTags\Data\ExtractorResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/hofff/contao-social-tags/src/Data/ExtractorResolver.php';

        return $container->privates['Hofff\\Contao\\SocialTags\\Data\\ExtractorResolver'] = new \Hofff\Contao\SocialTags\Data\ExtractorResolver(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['Hofff\\Contao\\SocialTags\\Data\\Extractor\\PageExtractor'] ?? $container->load('getPageExtractorService'));
            yield 1 => ($container->privates['Hofff\\Contao\\SocialTags\\Data\\Extractor\\NewsExtractor'] ?? $container->load('getNewsExtractorService'));
            yield 2 => ($container->privates['Hofff\\Contao\\SocialTags\\Data\\Extractor\\CalendarEventsExtractor'] ?? $container->load('getCalendarEventsExtractorService'));
            yield 3 => ($container->privates['Hofff\\Contao\\SocialTags\\Data\\Extractor\\FaqExtractor'] ?? $container->load('getFaqExtractorService'));
        }, 4));
    }
}
