<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormSendViaEmailExtendedService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'FormAdd\EventListener\FormSendViaEmailExtended' shared autowired service.
     *
     * @return \FormAdd\EventListener\FormSendViaEmailExtended
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/FormAdd/EventListener/FormSendViaEmailExtended.php';

        return $container->services['FormAdd\\EventListener\\FormSendViaEmailExtended'] = new \FormAdd\EventListener\FormSendViaEmailExtended();
    }
}
