<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFixRefererListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Terminal42\DcawizardBundle\EventListener\FixRefererListener' shared autowired service.
     *
     * @return \Terminal42\DcawizardBundle\EventListener\FixRefererListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/dcawizard/src/EventListener/FixRefererListener.php';

        return $container->services['Terminal42\\DcawizardBundle\\EventListener\\FixRefererListener'] = new \Terminal42\DcawizardBundle\EventListener\FixRefererListener(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->services['Codefog\\HasteBundle\\UrlParser'] ?? $container->load('getUrlParserService')));
    }
}
