<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Terminal42\NotificationCenterBundle\EventListener\Backend\DataContainer\FormListener' shared service.
     *
     * @return \Terminal42\NotificationCenterBundle\EventListener\Backend\DataContainer\FormListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/EventListener/Backend/DataContainer/FormListener.php';

        return $container->services['Terminal42\\NotificationCenterBundle\\EventListener\\Backend\\DataContainer\\FormListener'] = new \Terminal42\NotificationCenterBundle\EventListener\Backend\DataContainer\FormListener(($container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'] ?? $container->load('getNotificationCenterService')));
    }
}
