<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFacebookLintActionService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Hofff\Contao\SocialTags\Action\FacebookLintAction' shared service.
     *
     * @return \Hofff\Contao\SocialTags\Action\FacebookLintAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/hofff/contao-social-tags/src/Action/FacebookLintAction.php';

        return $container->services['Hofff\\Contao\\SocialTags\\Action\\FacebookLintAction'] = new \Hofff\Contao\SocialTags\Action\FacebookLintAction(($container->services['contao.framework'] ?? $container->getContao_FrameworkService()));
    }
}
