<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGatewayRegistryService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'Terminal42\NotificationCenterBundle\Gateway\GatewayRegistry' shared service.
     *
     * @return \Terminal42\NotificationCenterBundle\Gateway\GatewayRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/Gateway/GatewayRegistry.php';

        return $container->privates['Terminal42\\NotificationCenterBundle\\Gateway\\GatewayRegistry'] = new \Terminal42\NotificationCenterBundle\Gateway\GatewayRegistry(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['Terminal42\\NotificationCenterBundle\\Gateway\\MailerGateway'] ?? $container->load('getMailerGatewayService'));
        }, 1));
    }
}
