<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGutscheinwerftCallbackService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Digiwerft\Gutscheinwerft\DataContainer\GutscheinwerftCallback' shared autowired service.
     *
     * @return \Digiwerft\Gutscheinwerft\DataContainer\GutscheinwerftCallback
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/digiwerft/gutscheinwerft/src/DataContainer/GutscheinwerftCallback.php';

        return $container->services['Digiwerft\\Gutscheinwerft\\DataContainer\\GutscheinwerftCallback'] = new \Digiwerft\Gutscheinwerft\DataContainer\GutscheinwerftCallback();
    }
}
