<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetOptionsBridgeService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'MenAtWork\MultiColumnWizardBundle\EventListener\Mcw\GetOptionsBridge' shared service.
     *
     * @return \MenAtWork\MultiColumnWizardBundle\EventListener\Mcw\GetOptionsBridge
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/menatwork/contao-multicolumnwizard-bundle/src/EventListener/Mcw/GetOptionsBridge.php';

        $a = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->privates['MenAtWork\\MultiColumnWizardBundle\\EventListener\\Mcw\\GetOptionsBridge'])) {
            return $container->privates['MenAtWork\\MultiColumnWizardBundle\\EventListener\\Mcw\\GetOptionsBridge'];
        }

        return $container->privates['MenAtWork\\MultiColumnWizardBundle\\EventListener\\Mcw\\GetOptionsBridge'] = new \MenAtWork\MultiColumnWizardBundle\EventListener\Mcw\GetOptionsBridge($a);
    }
}
