<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIvo_Loadscripts_ReplacedynamicscripttagslistenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'ivo.loadscripts.replacedynamicscripttagslistener' shared autowired service.
     *
     * @return \Ivo\LoadScripts\EventListener\ReplaceDynamicScriptTagsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ivoschimani/loadscripts/src/EventListener/ReplaceDynamicScriptTagsListener.php';

        return $container->services['ivo.loadscripts.replacedynamicscripttagslistener'] = new \Ivo\LoadScripts\EventListener\ReplaceDynamicScriptTagsListener();
    }
}
