<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInitializeSystemService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'MenAtWork\MultiColumnWizardBundle\EventListener\Contao\InitializeSystem' shared service.
     *
     * @return \MenAtWork\MultiColumnWizardBundle\EventListener\Contao\InitializeSystem
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/menatwork/contao-multicolumnwizard-bundle/src/EventListener/Contao/InitializeSystem.php';

        return $container->services['MenAtWork\\MultiColumnWizardBundle\\EventListener\\Contao\\InitializeSystem'] = new \MenAtWork\MultiColumnWizardBundle\EventListener\Contao\InitializeSystem(($container->services['MenAtWork\\MultiColumnWizardBundle\\Service\\ContaoApiService'] ?? $container->load('getContaoApiServiceService')));
    }
}
