<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoadLanguageFileListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Hofff\Contao\SocialTags\EventListener\Hook\LoadLanguageFileListener' shared service.
     *
     * @return \Hofff\Contao\SocialTags\EventListener\Hook\LoadLanguageFileListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/hofff/contao-social-tags/src/EventListener/Hook/LoadLanguageFileListener.php';

        return $container->services['Hofff\\Contao\\SocialTags\\EventListener\\Hook\\LoadLanguageFileListener'] = new \Hofff\Contao\SocialTags\EventListener\Hook\LoadLanguageFileListener(($container->services['contao.framework'] ?? $container->getContao_FrameworkService()), ($container->privates['Hofff\\Contao\\SocialTags\\Data\\ExtractorResolver'] ?? $container->load('getExtractorResolverService')));
    }
}
