<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailerAttachmentsListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'Terminal42\NotificationCenterBundle\EventListener\MailerAttachmentsListener' shared service.
     *
     * @return \Terminal42\NotificationCenterBundle\EventListener\MailerAttachmentsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/EventListener/MailerAttachmentsListener.php';

        $a = ($container->privates['Terminal42\\NotificationCenterBundle\\BulkyItem\\BulkyItemStorage'] ?? $container->load('getBulkyItemStorageService'));

        if (isset($container->privates['Terminal42\\NotificationCenterBundle\\EventListener\\MailerAttachmentsListener'])) {
            return $container->privates['Terminal42\\NotificationCenterBundle\\EventListener\\MailerAttachmentsListener'];
        }

        return $container->privates['Terminal42\\NotificationCenterBundle\\EventListener\\MailerAttachmentsListener'] = new \Terminal42\NotificationCenterBundle\EventListener\MailerAttachmentsListener($a);
    }
}
