<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModuleListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Terminal42\NotificationCenterBundle\EventListener\Backend\DataContainer\ModuleListener' shared service.
     *
     * @return \Terminal42\NotificationCenterBundle\EventListener\Backend\DataContainer\ModuleListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/EventListener/Backend/DataContainer/ModuleListener.php';

        return $container->services['Terminal42\\NotificationCenterBundle\\EventListener\\Backend\\DataContainer\\ModuleListener'] = new \Terminal42\NotificationCenterBundle\EventListener\Backend\DataContainer\ModuleListener(($container->privates['Terminal42\\NotificationCenterBundle\\Config\\ConfigLoader'] ?? $container->load('getConfigLoaderService')), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'] ?? $container->load('getNotificationCenterService')));
    }
}
