<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Terminal42\NotificationCenterBundle\EventListener\Backend\DataContainer\MessageListener' shared service.
     *
     * @return \Terminal42\NotificationCenterBundle\EventListener\Backend\DataContainer\MessageListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/EventListener/Backend/DataContainer/MessageListener.php';

        return $container->services['Terminal42\\NotificationCenterBundle\\EventListener\\Backend\\DataContainer\\MessageListener'] = new \Terminal42\NotificationCenterBundle\EventListener\Backend\DataContainer\MessageListener(($container->privates['Terminal42\\NotificationCenterBundle\\Backend\\AutoSuggester'] ?? $container->load('getAutoSuggesterService')), ($container->privates['Terminal42\\NotificationCenterBundle\\Config\\ConfigLoader'] ?? $container->load('getConfigLoaderService')), ($container->services['contao.framework'] ?? $container->getContao_FrameworkService()), ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService()), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService()), ($container->services['contao.intl.locales'] ?? $container->getContao_Intl_LocalesService()));
    }
}
