<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailerAsynchronousReceiptUpdateListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'Terminal42\NotificationCenterBundle\EventListener\MailerAsynchronousReceiptUpdateListener' shared service.
     *
     * @return \Terminal42\NotificationCenterBundle\EventListener\MailerAsynchronousReceiptUpdateListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/EventListener/MailerAsynchronousReceiptUpdateListener.php';

        $a = ($container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'] ?? $container->load('getNotificationCenterService'));

        if (isset($container->privates['Terminal42\\NotificationCenterBundle\\EventListener\\MailerAsynchronousReceiptUpdateListener'])) {
            return $container->privates['Terminal42\\NotificationCenterBundle\\EventListener\\MailerAsynchronousReceiptUpdateListener'];
        }

        return $container->privates['Terminal42\\NotificationCenterBundle\\EventListener\\MailerAsynchronousReceiptUpdateListener'] = new \Terminal42\NotificationCenterBundle\EventListener\MailerAsynchronousReceiptUpdateListener($a);
    }
}
