<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationCenterRuntimeService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'Terminal42\NotificationCenterBundle\Twig\NotificationCenterRuntime' shared service.
     *
     * @return \Terminal42\NotificationCenterBundle\Twig\NotificationCenterRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/Twig/NotificationCenterRuntime.php';

        $a = ($container->services['contao.framework'] ?? $container->getContao_FrameworkService());

        if (isset($container->privates['Terminal42\\NotificationCenterBundle\\Twig\\NotificationCenterRuntime'])) {
            return $container->privates['Terminal42\\NotificationCenterBundle\\Twig\\NotificationCenterRuntime'];
        }
        $b = ($container->privates['Terminal42\\NotificationCenterBundle\\BulkyItem\\BulkyItemStorage'] ?? $container->load('getBulkyItemStorageService'));

        if (isset($container->privates['Terminal42\\NotificationCenterBundle\\Twig\\NotificationCenterRuntime'])) {
            return $container->privates['Terminal42\\NotificationCenterBundle\\Twig\\NotificationCenterRuntime'];
        }

        return $container->privates['Terminal42\\NotificationCenterBundle\\Twig\\NotificationCenterRuntime'] = new \Terminal42\NotificationCenterBundle\Twig\NotificationCenterRuntime($a, $b);
    }
}
