<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationTypeRegistryService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'Terminal42\NotificationCenterBundle\NotificationType\NotificationTypeRegistry' shared service.
     *
     * @return \Terminal42\NotificationCenterBundle\NotificationType\NotificationTypeRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/NotificationType/NotificationTypeRegistry.php';

        return $container->privates['Terminal42\\NotificationCenterBundle\\NotificationType\\NotificationTypeRegistry'] = new \Terminal42\NotificationCenterBundle\NotificationType\NotificationTypeRegistry(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['Terminal42\\NotificationCenterBundle\\NotificationType\\FormGeneratorNotificationType'] ?? $container->load('getFormGeneratorNotificationTypeService'));
            yield 1 => ($container->privates['Terminal42\\NotificationCenterBundle\\NotificationType\\LostPasswordNotificationType'] ?? $container->load('getLostPasswordNotificationTypeService'));
            yield 2 => ($container->privates['Terminal42\\NotificationCenterBundle\\NotificationType\\MemberActivationNotificationType'] ?? $container->load('getMemberActivationNotificationTypeService'));
            yield 3 => ($container->privates['Terminal42\\NotificationCenterBundle\\NotificationType\\MemberRegistrationNotificationType'] ?? $container->load('getMemberRegistrationNotificationTypeService'));
            yield 4 => ($container->privates['Terminal42\\NotificationCenterBundle\\NotificationType\\MemberPersonalDataNotificationType'] ?? $container->load('getMemberPersonalDataNotificationTypeService'));
        }, 5));
    }
}
