<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsExtractorService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'Hofff\Contao\SocialTags\Data\Extractor\NewsExtractor' shared service.
     *
     * @return \Hofff\Contao\SocialTags\Data\Extractor\NewsExtractor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/hofff/contao-social-tags/src/Data/Extractor.php';
        include_once \dirname(__DIR__, 4).'/vendor/hofff/contao-social-tags/src/Data/Extractor/AbstractExtractor.php';
        include_once \dirname(__DIR__, 4).'/vendor/hofff/contao-social-tags/src/Data/OpenGraph/OpenGraphExtractor.php';
        include_once \dirname(__DIR__, 4).'/vendor/hofff/contao-social-tags/src/Data/TwitterCards/TwitterCardsExtractor.php';
        include_once \dirname(__DIR__, 4).'/vendor/hofff/contao-social-tags/src/Data/OpenGraph/OpenGraphExtractorImagePlugin.php';
        include_once \dirname(__DIR__, 4).'/vendor/hofff/contao-social-tags/src/Data/OpenGraph/OpenGraphExtractorPlugin.php';
        include_once \dirname(__DIR__, 4).'/vendor/hofff/contao-social-tags/src/Data/TwitterCards/TwitterCardsExtractorPlugin.php';
        include_once \dirname(__DIR__, 4).'/vendor/hofff/contao-social-tags/src/Data/Extractor/NewsExtractor.php';

        return $container->privates['Hofff\\Contao\\SocialTags\\Data\\Extractor\\NewsExtractor'] = new \Hofff\Contao\SocialTags\Data\Extractor\NewsExtractor(($container->services['contao.framework'] ?? $container->getContao_FrameworkService()), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->services['contao.routing.response_context_accessor'] ?? $container->load('getContao_Routing_ResponseContextAccessorService')), ($container->services['contao.insert_tag.parser'] ?? $container->load('getContao_InsertTag_ParserService')), \dirname(__DIR__, 4));
    }
}
