<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationCenterService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'Terminal42\NotificationCenterBundle\NotificationCenter' shared service.
     *
     * @return \Terminal42\NotificationCenterBundle\NotificationCenter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/NotificationCenter.php';

        $a = ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService());

        if (isset($container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'])) {
            return $container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'];
        }
        $b = ($container->privates['Terminal42\\NotificationCenterBundle\\Gateway\\GatewayRegistry'] ?? $container->load('getGatewayRegistryService'));

        if (isset($container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'])) {
            return $container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'];
        }
        $c = ($container->privates['Terminal42\\NotificationCenterBundle\\Config\\ConfigLoader'] ?? $container->load('getConfigLoaderService'));

        if (isset($container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'])) {
            return $container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'];
        }
        $d = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'])) {
            return $container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'];
        }
        $e = ($container->privates['Terminal42\\NotificationCenterBundle\\BulkyItem\\BulkyItemStorage'] ?? $container->load('getBulkyItemStorageService'));

        if (isset($container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'])) {
            return $container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'];
        }
        $f = ($container->services['Codefog\\HasteBundle\\StringParser'] ?? $container->load('getStringParserService'));

        if (isset($container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'])) {
            return $container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'];
        }

        return $container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'] = new \Terminal42\NotificationCenterBundle\NotificationCenter($a, ($container->privates['Terminal42\\NotificationCenterBundle\\NotificationType\\NotificationTypeRegistry'] ?? $container->load('getNotificationTypeRegistryService')), $b, $c, $d, ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), $e, $f, NULL);
    }
}
