<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Terminal42\NotificationCenterBundle\EventListener\Backend\DataContainer\NotificationListener' shared service.
     *
     * @return \Terminal42\NotificationCenterBundle\EventListener\Backend\DataContainer\NotificationListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/EventListener/Backend/DataContainer/NotificationListener.php';

        return $container->services['Terminal42\\NotificationCenterBundle\\EventListener\\Backend\\DataContainer\\NotificationListener'] = new \Terminal42\NotificationCenterBundle\EventListener\Backend\DataContainer\NotificationListener(($container->privates['Terminal42\\NotificationCenterBundle\\NotificationType\\NotificationTypeRegistry'] ?? $container->load('getNotificationTypeRegistryService')));
    }
}
