<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOpenGraphTypeOptionsService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Hofff\Contao\SocialTags\EventListener\Dca\OpenGraphTypeOptions' shared service.
     *
     * @return \Hofff\Contao\SocialTags\EventListener\Dca\OpenGraphTypeOptions
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/hofff/contao-social-tags/src/EventListener/Dca/OpenGraphTypeOptions.php';

        return $container->services['Hofff\\Contao\\SocialTags\\EventListener\\Dca\\OpenGraphTypeOptions'] = new \Hofff\Contao\SocialTags\EventListener\Dca\OpenGraphTypeOptions($container->parameters['hofff.contao_social_tags.open_graph_types']);
    }
}
