<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageSocialTagsListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Hofff\Contao\SocialTags\EventListener\Hook\PageSocialTagsListener' shared service.
     *
     * @return \Hofff\Contao\SocialTags\EventListener\Hook\PageSocialTagsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/hofff/contao-social-tags/src/EventListener/Hook/SocialTagsDataAwareListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/hofff/contao-social-tags/src/EventListener/Hook/PageSocialTagsListener.php';

        return $container->services['Hofff\\Contao\\SocialTags\\EventListener\\Hook\\PageSocialTagsListener'] = new \Hofff\Contao\SocialTags\EventListener\Hook\PageSocialTagsListener(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->privates['Hofff\\Contao\\SocialTags\\Data\\SocialTagsFactory'] ?? $container->load('getSocialTagsFactoryService')));
    }
}
