<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Terminal42\NotificationCenterBundle\EventListener\RegistrationListener' shared service.
     *
     * @return \Terminal42\NotificationCenterBundle\EventListener\RegistrationListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/EventListener/RegistrationListener.php';

        return $container->services['Terminal42\\NotificationCenterBundle\\EventListener\\RegistrationListener'] = new \Terminal42\NotificationCenterBundle\EventListener\RegistrationListener(($container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'] ?? $container->load('getNotificationCenterService')), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->services['Codefog\\HasteBundle\\Formatter'] ?? $container->getFormatterService()));
    }
}
