<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSocialTagsFactoryService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'Hofff\Contao\SocialTags\Data\SocialTagsFactory' shared service.
     *
     * @return \Hofff\Contao\SocialTags\Data\SocialTagsFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/hofff/contao-social-tags/src/Data/SocialTagsFactory.php';

        return $container->privates['Hofff\\Contao\\SocialTags\\Data\\SocialTagsFactory'] = new \Hofff\Contao\SocialTags\Data\SocialTagsFactory(($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService()), ($container->services['contao.framework'] ?? $container->getContao_FrameworkService()), new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['Hofff\\Contao\\SocialTags\\Data\\OpenGraph\\OpenGraphFactory'] ?? $container->load('getOpenGraphFactoryService'));
            yield 1 => ($container->privates['Hofff\\Contao\\SocialTags\\Data\\TwitterCards\\TwitterCardsFactory'] ?? $container->load('getTwitterCardsFactoryService'));
        }, 2));
    }
}
