<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSetInsertTagsForMetaDataService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'AutometaBundle\EventListener\SetInsertTagsForMetaData' shared autowired service.
     *
     * @return \AutometaBundle\EventListener\SetInsertTagsForMetaData
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AutometaBundle/EventListener/SetInsertTagsForMetaData.php';

        return $container->services['AutometaBundle\\EventListener\\SetInsertTagsForMetaData'] = new \AutometaBundle\EventListener\SetInsertTagsForMetaData();
    }
}
