<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTerminal42UrlRewrite_Listener_InsertTagsService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'terminal42_url_rewrite.listener.insert_tags' shared service.
     *
     * @return \Terminal42\UrlRewriteBundle\EventListener\InsertTagsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-url-rewrite/src/EventListener/InsertTagsListener.php';

        return $container->services['terminal42_url_rewrite.listener.insert_tags'] = new \Terminal42\UrlRewriteBundle\EventListener\InsertTagsListener(($container->services['contao.framework'] ?? $container->getContao_FrameworkService()));
    }
}
