<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTerminal42UrlRewrite_QrCodeGeneratorService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'terminal42_url_rewrite.qr_code_generator' shared service.
     *
     * @return \Terminal42\UrlRewriteBundle\QrCodeGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-url-rewrite/src/QrCodeGenerator.php';

        return $container->privates['terminal42_url_rewrite.qr_code_generator'] = new \Terminal42\UrlRewriteBundle\QrCodeGenerator(($container->services['router'] ?? $container->getRouterService()));
    }
}
