<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTerminal42UrlRewrite_Listener_RewriteContainerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'terminal42_url_rewrite.listener.rewrite_container' shared service.
     *
     * @return \Terminal42\UrlRewriteBundle\EventListener\RewriteContainerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-url-rewrite/src/EventListener/RewriteContainerListener.php';

        return $container->services['terminal42_url_rewrite.listener.rewrite_container'] = new \Terminal42\UrlRewriteBundle\EventListener\RewriteContainerListener(($container->privates['terminal42_url_rewrite.qr_code_generator'] ?? $container->load('getTerminal42UrlRewrite_QrCodeGeneratorService')), ($container->services['router'] ?? $container->getRouterService()), $container->targetDir.'', ($container->services['contao.framework'] ?? $container->getContao_FrameworkService()), ($container->services['.container.private.filesystem'] ?? ($container->services['.container.private.filesystem'] = new \Symfony\Component\Filesystem\Filesystem())));
    }
}
