<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwitterCardsFactoryService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'Hofff\Contao\SocialTags\Data\TwitterCards\TwitterCardsFactory' shared service.
     *
     * @return \Hofff\Contao\SocialTags\Data\TwitterCards\TwitterCardsFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/hofff/contao-social-tags/src/Data/DataFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/hofff/contao-social-tags/src/Data/TwitterCards/TwitterCardsFactory.php';

        return $container->privates['Hofff\\Contao\\SocialTags\\Data\\TwitterCards\\TwitterCardsFactory'] = new \Hofff\Contao\SocialTags\Data\TwitterCards\TwitterCardsFactory(($container->privates['Hofff\\Contao\\SocialTags\\Data\\ExtractorResolver'] ?? $container->load('getExtractorResolverService')));
    }
}
