<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTerminal42UrlRewrite_RewriteControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'terminal42_url_rewrite.rewrite_controller' shared service.
     *
     * @return \Terminal42\UrlRewriteBundle\Controller\RewriteController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-url-rewrite/src/Controller/RewriteController.php';

        return $container->services['terminal42_url_rewrite.rewrite_controller'] = new \Terminal42\UrlRewriteBundle\Controller\RewriteController(($container->privates['terminal42_url_rewrite.provider.chain'] ?? $container->load('getTerminal42UrlRewrite_Provider_ChainService')), ($container->services['contao.insert_tag.parser'] ?? $container->load('getContao_InsertTag_ParserService')));
    }
}
