<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTerminal42UrlRewrite_Provider_ChainService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'terminal42_url_rewrite.provider.chain' shared service.
     *
     * @return \Terminal42\UrlRewriteBundle\ConfigProvider\ChainConfigProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-url-rewrite/src/ConfigProvider/ConfigProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-url-rewrite/src/ConfigProvider/ChainConfigProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-url-rewrite/src/ConfigProvider/BundleConfigProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-url-rewrite/src/ConfigProvider/DatabaseConfigProvider.php';

        $container->privates['terminal42_url_rewrite.provider.chain'] = $instance = new \Terminal42\UrlRewriteBundle\ConfigProvider\ChainConfigProvider();

        $instance->addProvider(new \Terminal42\UrlRewriteBundle\ConfigProvider\BundleConfigProvider([]));
        $instance->addProvider(new \Terminal42\UrlRewriteBundle\ConfigProvider\DatabaseConfigProvider(($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService())));

        return $instance;
    }
}
