<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTerminal42UrlRewrite_QrCodeControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'terminal42_url_rewrite.qr_code_controller' shared service.
     *
     * @return \Terminal42\UrlRewriteBundle\Controller\QrCodeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-url-rewrite/src/Controller/QrCodeController.php';

        return $container->services['terminal42_url_rewrite.qr_code_controller'] = new \Terminal42\UrlRewriteBundle\Controller\QrCodeController(($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService()), ($container->privates['terminal42_url_rewrite.qr_code_generator'] ?? $container->load('getTerminal42UrlRewrite_QrCodeGeneratorService')), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->services['router'] ?? $container->getRouterService()), ($container->services['uri_signer'] ?? ($container->services['uri_signer'] = new \Symfony\Component\HttpKernel\UriSigner($container->getEnv('APP_SECRET')))));
    }
}
