<?php

namespace Container8bhmPUq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getYourClassNameService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'ContentElements\YourClassName' shared autowired service.
     *
     * @return \ContentElements\YourClassName
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['ContentElements\\YourClassName'] = new \ContentElements\YourClassName();
    }
}
