<?php

### INSTALL SCRIPT START ###
$GLOBALS['TL_CONFIG']['licenseAccepted'] = true;
$GLOBALS['TL_CONFIG']['installPassword'] = '$2y$10$Sqsc/OSlLhTeXwXJxkRDtOBImhXQmTlfQas2Ty5dobugUGB4i5pSW';
$GLOBALS['TL_CONFIG']['adminEmail'] = 'gutscheinwerft@digiwerft.de';
$GLOBALS['TL_CONFIG']['allowedAttributes'] = 'a:20:{i:0;a:2:{s:3:"key";s:1:"*";s:5:"value";s:103:"aria-*,class,data-*,dir,hidden,id,itemid,itemprop,itemref,itemscope,itemtype,lang,style,title,translate";}i:1;a:2:{s:3:"key";s:1:"a";s:5:"value";s:48:"download,href,hreflang,referrerpolicy,rel,target";}i:2;a:2:{s:3:"key";s:4:"area";s:5:"value";s:50:"alt,coords,download,href,hreflang,rel,shape,target";}i:3;a:2:{s:3:"key";s:5:"audio";s:5:"value";s:52:"autoplay,controls,crossorigin,loop,muted,preload,src";}i:4;a:2:{s:3:"key";s:3:"col";s:5:"value";s:4:"span";}i:5;a:2:{s:3:"key";s:8:"colgroup";s:5:"value";s:4:"span";}i:6;a:2:{s:3:"key";s:7:"details";s:5:"value";s:4:"open";}i:7;a:2:{s:3:"key";s:3:"div";s:5:"value";s:5:"style";}i:8;a:2:{s:3:"key";s:6:"iframe";s:5:"value";s:33:"allow,frameborder,src,style,title";}i:9;a:2:{s:3:"key";s:3:"img";s:5:"value";s:90:"alt,crossorigin,decoding,height,ismap,loading,referrerpolicy,sizes,src,srcset,usemap,width";}i:10;a:2:{s:3:"key";s:3:"map";s:5:"value";s:4:"name";}i:11;a:2:{s:3:"key";s:2:"ol";s:5:"value";s:19:"reversed,start,type";}i:12;a:2:{s:3:"key";s:6:"script";s:5:"value";s:28:"async,categories,charset,src";}i:13;a:2:{s:3:"key";s:6:"source";s:5:"value";s:27:"media,sizes,src,srcset,type";}i:14;a:2:{s:3:"key";s:5:"style";s:5:"value";s:5:"media";}i:15;a:2:{s:3:"key";s:5:"table";s:5:"value";s:43:"border,cellpadding,cellspacing,height,width";}i:16;a:2:{s:3:"key";s:2:"td";s:5:"value";s:28:"colspan,height,rowspan,width";}i:17;a:2:{s:3:"key";s:2:"th";s:5:"value";s:28:"colspan,height,rowspan,width";}i:18;a:2:{s:3:"key";s:4:"time";s:5:"value";s:8:"datetime";}i:19;a:2:{s:3:"key";s:5:"video";s:5:"value";s:97:"autoplay,controls,controlslist,crossorigin,height,loop,muted,playsinline,poster,preload,src,width";}}';
$GLOBALS['TL_CONFIG']['defaultUser'] = 3;
$GLOBALS['TL_CONFIG']['defaultGroup'] = 1;
$GLOBALS['TL_CONFIG']['defaultChmod'] = 'a:12:{i:0;s:2:"u1";i:1;s:2:"u2";i:2;s:2:"u3";i:3;s:2:"u4";i:4;s:2:"u5";i:5;s:2:"u6";i:6;s:2:"g1";i:7;s:2:"g2";i:8;s:2:"g3";i:9;s:2:"g4";i:10;s:2:"g5";i:11;s:2:"g6";}';
$GLOBALS['TL_CONFIG']['allowedTags'] = '<script><a><abbr><acronym><address><area><article><aside><audio><b><bdi><bdo><big><blockquote><br><button><caption><cite><code><col><colgroup><data><datalist><dd><del><details><dfn><div><dl><dt><em><fieldset><figcaption><figure><footer><form><h1><h2><h3><h4><h5><h6><header><hgroup><hr><i><img><input><ins><kbd><label><legend><li><map><mark><menu><nav><ol><optgroup><option><output><p><picture><pre><q><s><samp><section><select><small><source><span><strong><style><sub><summary><sup><table><tbody><td><textarea><tfoot><th><thead><time><tr><tt><u><ul><var><video><wbr>';
$GLOBALS['TL_CONFIG']['headtext'] = '{{iflng::de}}Die clevere Gutscheinlösung für eCommerce, Sport, Hotellerie & Gastronomie{{iflng::en}}The smart Giftcard solution for eCommerce, Sports, Hospitality & Gastronomy{{iflng}}';
$GLOBALS['TL_CONFIG']['gutscheinwerft_user'] = 'api_digiwerft@digi-werft.de';
$GLOBALS['TL_CONFIG']['gutscheinwerft_pass'] = '';
### INSTALL SCRIPT STOP ###
