<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8bhmPUq\Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8bhmPUq/Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer.php') {
    touch(__DIR__.'/Container8bhmPUq.legacy');

    return;
}

if (!\class_exists(Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, false)) {
    \class_alias(\Container8bhmPUq\Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, false);
}

return new \Container8bhmPUq\Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer([
    'container.build_hash' => '8bhmPUq',
    'container.build_id' => '56d40f92',
    'container.build_time' => 1763967883,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8bhmPUq');
