nelmio_security:
  clickjacking:
    paths:
      "^/datenschutz-app.html": ALLOW
      "^/impressum-app.html": ALLOW
contao:
  image:
    sizes:
      image_text_full:
        width: 1626
        height: 1135
        resize_mode: box
      image_text:
        width: 812
        height: 512
        resize_mode: crop
      image_slider:
        width: 837
        height: 623
        resize_mode: crop
      icon_boxes_image:
        width: 960
        height: 476
        resize_mode: box
      testimonial_image:
        width: 426
        height: 602
        resize_mode: crop
      icon_with_text:
        width: 384
        height: 384
        resize_mode: box
        items:
          - media: "(max-width: 767px)"
            width: 250
            height: 250
            resize_mode: box
      testimonial_logo:
        width: 105
        height: 105
        resize_mode: box
      news_list:
        width: 742
        height: 385
        resize_mode: crop
